import mongoose, { Document, Schema } from 'mongoose';

/**
 * Report type enum
 */
export enum ReportType {
  FINANCIAL = 'financial',
  PROGRESS = 'progress',
  SUMMARY = 'summary',
  CUSTOM = 'custom'
}

/**
 * Report interface
 */
export interface IReport extends Document {
  projectId?: mongoose.Types.ObjectId; // Optional, can be project-specific or general
  generatedBy: mongoose.Types.ObjectId; // Accounts user who generated the report
  type: ReportType;
  title: string;
  data: Record<string, any>; // Flexible data structure for different report types
  filePath?: string; // If report is exported to a file
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Report schema definition
 */
const ReportSchema: Schema = new Schema(
  {
    projectId: {
      type: Schema.Types.ObjectId,
      ref: 'Project',
      default: null
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by user ID is required']
    },
    type: {
      type: String,
      enum: Object.values(ReportType),
      required: [true, 'Report type is required']
    },
    title: {
      type: String,
      required: [true, 'Report title is required'],
      trim: true
    },
    data: {
      type: Schema.Types.Mixed,
      required: [true, 'Report data is required']
    },
    filePath: {
      type: String,
      trim: true
    },
    description: {
      type: String,
      trim: true
    }
  },
  {
    timestamps: true,
    collection: 'reports'
  }
);

// Indexes for faster queries
ReportSchema.index({ projectId: 1 });
ReportSchema.index({ generatedBy: 1 });
ReportSchema.index({ type: 1 });
ReportSchema.index({ createdAt: -1 });

export const Report = mongoose.model<IReport>('Report', ReportSchema);

